In [ ]:
!python -m pip install -U woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

In [ ]:
%pip install python-woc

Collecting python-woc
  Downloading python_woc-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /usr/local/lib/python3.12/dist-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from python-woc) (0.28.1)
Collecting python-lzf<0.3.0,>=0.2.4 (from python-woc)
  Downloading python_lzf-0.2.6.tar.gz (9.8 kB)
  Preparing metadata (setup.py) ... done
Collecting rapidgzip<0.15.0,>=0.14.3 (from python-woc)
  Downloading rapidgzip-0.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from python-woc) (4.67.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.15.0)
Downloading python_woc-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 3.2 MB/s eta 0:00:00
Downloading rapidgzip-0.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 3.0 MB/s eta 0:00:00
Building wheels for collected packages: python-lzf
  Building wheel for python-lzf (setup.py) ... done
  Created wheel for python-lzf: filename=python_lzf-0.2.6-cp312-cp312-linux_x86_64.whl size=18589 sha256=aecc9dd7e9a5183adafc0205dd5c037ff0b1e92a9abdc461c8ea022bafafa7a0
  Stored in directory: /root/.cache/pip/wheels/0c/9b/11/c1baf6f3e2841c29980d34aaee5f98ac97de91ef429c068ef4
Successfully built python-lzf
Installing collected packages: python-lzf, rapidgzip, python-woc
Successfully installed python-lzf-0.2.6 python-woc-0.4.1 rapidgzip-0.14.5

In [ ]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
df_projects = pd.read_csv("net2prj.csv")

my_projects = df_projects[df_projects['netID'] == 'sydlwils']

projects = my_projects['WoC'].tolist()

print(projects)

list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

['parflow_parflow', 'inab_wes-backend', 'knossos-project_knossos', 'project-konda_pattern-based-quality-analysis', 'wistaria_materiappsinstaller', 'wtmatlock_flanker', 'openmd_openmd', 'google_uis-rnn', 'leftygray_cascade_calculations', 'nrel_openstudio-server']

                                       sha1          project
0  000b054f839a0eaba1d76e97da534b18df0e41f0  parflow_parflow

In [ ]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

 10%|█         | 335/3194 [06:54<58:45,  1.23s/it]

Got Errors {'a253882c8d769235a4d3bdd0f6fd46c341364f03': 'Key a253882c8d769235a4d3bdd0f6fd46c341364f03 not found in /da5_fast/All.sha1c/commit_34.tch'}

 13%|█▎        | 430/3194 [08:52<56:48,  1.23s/it]

Got Errors {'ce5e25d66ea8226a41dba05ac0aa6900de9c9fba': 'Key ce5e25d66ea8226a41dba05ac0aa6900de9c9fba not found in /da5_fast/All.sha1c/commit_78.tch'}

 16%|█▌        | 499/3194 [10:17<55:27,  1.23s/it]

Got Errors {'ef2e5c22a9c984b82bdf550628d73dae079b10c5': 'Key ef2e5c22a9c984b82bdf550628d73dae079b10c5 not found in /da5_fast/All.sha1c/commit_111.tch'}

 26%|██▌       | 832/3194 [17:10<48:24,  1.23s/it]

Got Errors {'27108dad81ca4501f6be9ace82a880cd848f6ced': 'Key 27108dad81ca4501f6be9ace82a880cd848f6ced not found in /da5_fast/All.sha1c/commit_39.tch'}

 27%|██▋       | 852/3194 [17:34<47:55,  1.23s/it]

Got Errors {'30dd8a9b670e971d0c5627fd7837774fc08be64b': 'Key 30dd8a9b670e971d0c5627fd7837774fc08be64b not found in /da5_fast/All.sha1c/commit_48.tch'}

 29%|██▊       | 918/3194 [18:55<46:40,  1.23s/it]

Got Errors {'50162621ca1550054ed54c1a366f833b448fd930': 'Key 50162621ca1550054ed54c1a366f833b448fd930 not found in /da5_fast/All.sha1c/commit_80.tch'}

 30%|███       | 967/3194 [19:56<45:45,  1.23s/it]

Got Errors {'6667764c2eedca708eebf23370d328a3095e9ab2': 'Key 6667764c2eedca708eebf23370d328a3095e9ab2 not found in /da5_fast/All.sha1c/commit_102.tch'}

 32%|███▏      | 1011/3194 [20:51<45:17,  1.24s/it]

Got Errors {'7bc2f0ad856588b1b7c80bf0a799bd41de6509fb': 'Key 7bc2f0ad856588b1b7c80bf0a799bd41de6509fb not found in /da5_fast/All.sha1c/commit_123.tch'}

 32%|███▏      | 1019/3194 [21:01<45:09,  1.25s/it]

Got Errors {'7f658ec5b6677c6f3747ef0d676e23ddb44183bb': 'Key 7f658ec5b6677c6f3747ef0d676e23ddb44183bb not found in /da5_fast/All.sha1c/commit_127.tch'}

 34%|███▍      | 1081/3194 [22:17<43:15,  1.23s/it]

Got Errors {'9a145b1c3628218d98a0e18f2db082b38311a8d9': 'Key 9a145b1c3628218d98a0e18f2db082b38311a8d9 not found in /da5_fast/All.sha1c/commit_26.tch'}

 35%|███▍      | 1111/3194 [22:54<42:44,  1.23s/it]

Got Errors {'a7ed31ebd897a16f07ba12e6620e0e319ee386a5': 'Key a7ed31ebd897a16f07ba12e6620e0e319ee386a5 not found in /da5_fast/All.sha1c/commit_39.tch'}

 36%|███▋      | 1161/3194 [23:55<41:38,  1.23s/it]

Got Errors {'c015996b05be9320f76f9a8f4440ad8c03e29837': 'Key c015996b05be9320f76f9a8f4440ad8c03e29837 not found in /da5_fast/All.sha1c/commit_64.tch'}

 36%|███▋      | 1163/3194 [23:58<41:38,  1.23s/it]

Got Errors {'c0fd87ceb600aba8dd19d28bb8b1ad17e5e21b69': 'Key c0fd87ceb600aba8dd19d28bb8b1ad17e5e21b69 not found in /da5_fast/All.sha1c/commit_64.tch'}

 69%|██████▉   | 2207/3194 [45:30<20:28,  1.24s/it]

Got Errors {'07a06b77ac46716a3e86c641e8d444ee3b9ffd95': 'Key 07a06b77ac46716a3e86c641e8d444ee3b9ffd95 not found in /da5_fast/All.sha1c/commit_7.tch'}

 69%|██████▉   | 2208/3194 [45:31<20:25,  1.24s/it]

Got Errors {'0a5fcf2109fad65244315f7ff1356490735102cb': 'Key 0a5fcf2109fad65244315f7ff1356490735102cb not found in /da5_fast/All.sha1c/commit_10.tch'}

 69%|██████▉   | 2210/3194 [45:34<20:23,  1.24s/it]

Got Errors {'0ebbe5beee5d91a45cd21339d5fe8a6973217e73': 'Key 0ebbe5beee5d91a45cd21339d5fe8a6973217e73 not found in /da5_fast/All.sha1c/commit_14.tch'}

 69%|██████▉   | 2219/3194 [45:45<20:18,  1.25s/it]

Got Errors {'20560b4e688e7fdf540975b4f7d2f7cd6fd863da': 'Key 20560b4e688e7fdf540975b4f7d2f7cd6fd863da not found in /da5_fast/All.sha1c/commit_32.tch'}

 70%|██████▉   | 2221/3194 [45:47<20:12,  1.25s/it]

Got Errors {'2412cc39c0e14401dc5ce906bf641cabb69f359c': 'Key 2412cc39c0e14401dc5ce906bf641cabb69f359c not found in /da5_fast/All.sha1c/commit_36.tch'}

 70%|██████▉   | 2235/3194 [46:05<19:51,  1.24s/it]

Got Errors {'483fb216d1e851163c95b5d99f9c52f504c8d248': 'Key 483fb216d1e851163c95b5d99f9c52f504c8d248 not found in /da5_fast/All.sha1c/commit_72.tch'}

 71%|███████   | 2256/3194 [46:31<19:26,  1.24s/it]

Got Errors {'7c51484af2be8ab2ad39ab35d3928adf9136911d': 'Key 7c51484af2be8ab2ad39ab35d3928adf9136911d not found in /da5_fast/All.sha1c/commit_124.tch'}

 71%|███████   | 2260/3194 [46:36<19:18,  1.24s/it]

Got Errors {'84a31f099884c7de6fe99c63d6c4c2c32acc3d9f': 'Key 84a31f099884c7de6fe99c63d6c4c2c32acc3d9f not found in /da5_fast/All.sha1c/commit_4.tch'}

 71%|███████   | 2263/3194 [46:40<19:13,  1.24s/it]

Got Errors {'8b130473d20a39f174f3797d7f1354edb66c45cd': 'Key 8b130473d20a39f174f3797d7f1354edb66c45cd not found in /da5_fast/All.sha1c/commit_11.tch'}

 71%|███████   | 2264/3194 [46:41<19:11,  1.24s/it]

Got Errors {'8de477accd39cf70b9046002001167d5963ae904': 'Key 8de477accd39cf70b9046002001167d5963ae904 not found in /da5_fast/All.sha1c/commit_13.tch'}

 71%|███████▏  | 2279/3194 [47:00<18:56,  1.24s/it]

Got Errors {'b117498d22bab7d131750eafc25661aa424f03d9': 'Key b117498d22bab7d131750eafc25661aa424f03d9 not found in /da5_fast/All.sha1c/commit_49.tch'}

 71%|███████▏  | 2282/3194 [47:03<18:51,  1.24s/it]

Got Errors {'b72c2d06a91460f63965734f180fdccdab7171c2': 'Key b72c2d06a91460f63965734f180fdccdab7171c2 not found in /da5_fast/All.sha1c/commit_55.tch'}

 72%|███████▏  | 2284/3194 [47:06<18:49,  1.24s/it]

Got Errors {'ba31b39678529487c3c9b5ffc0bcdae18d764de6': 'Key ba31b39678529487c3c9b5ffc0bcdae18d764de6 not found in /da5_fast/All.sha1c/commit_58.tch', 'baa5da8608c366c91fc4112bd822ca87582648cf': 'Key baa5da8608c366c91fc4112bd822ca87582648cf not found in /da5_fast/All.sha1c/commit_58.tch'}

 72%|███████▏  | 2286/3194 [47:08<18:46,  1.24s/it]

Got Errors {'c0a1fa4ae326c93a07efc78c846ab227be9d51f5': 'Key c0a1fa4ae326c93a07efc78c846ab227be9d51f5 not found in /da5_fast/All.sha1c/commit_64.tch'}

 72%|███████▏  | 2299/3194 [47:24<18:31,  1.24s/it]

Got Errors {'de079bb7bcfb3af0c8186e3661435a38773170b6': 'Key de079bb7bcfb3af0c8186e3661435a38773170b6 not found in /da5_fast/All.sha1c/commit_94.tch'}

 72%|███████▏  | 2300/3194 [47:26<18:29,  1.24s/it]

Got Errors {'e0d8b38dc8d2efe5468613b2b419045476d24259': 'Key e0d8b38dc8d2efe5468613b2b419045476d24259 not found in /da5_fast/All.sha1c/commit_96.tch'}

 72%|███████▏  | 2304/3194 [47:31<18:23,  1.24s/it]

Got Errors {'ed02270a822af37458644535f2868ea4ff105471': 'Key ed02270a822af37458644535f2868ea4ff105471 not found in /da5_fast/All.sha1c/commit_109.tch'}

 74%|███████▍  | 2357/3194 [48:36<17:21,  1.24s/it]

Got Errors {'0cf91cfe42b884f7589912cd8f43bdb05f724861': 'Key 0cf91cfe42b884f7589912cd8f43bdb05f724861 not found in /da5_fast/All.sha1c/commit_12.tch'}

 78%|███████▊  | 2503/3194 [51:37<14:16,  1.24s/it]

Got Errors {'38ed80743566549eb30ea6cd70fc2765d842c568': 'Key 38ed80743566549eb30ea6cd70fc2765d842c568 not found in /da5_fast/All.sha1c/commit_56.tch'}

 82%|████████▏ | 2628/3194 [54:12<11:40,  1.24s/it]

Got Errors {'5eaa0afb9c96c7743c59c18476d983943103649a': 'Key 5eaa0afb9c96c7743c59c18476d983943103649a not found in /da5_fast/All.sha1c/commit_94.tch'}

 86%|████████▌ | 2740/3194 [56:31<09:20,  1.24s/it]

Got Errors {'7d8a92567d12e8a5c39a4af840c41c156eb312ac': 'Key 7d8a92567d12e8a5c39a4af840c41c156eb312ac not found in /da5_fast/All.sha1c/commit_125.tch'}

 87%|████████▋ | 2783/3194 [57:24<08:28,  1.24s/it]

Got Errors {'8a4ff54799af1e8405b21ea4b498e56560c78257': 'Key 8a4ff54799af1e8405b21ea4b498e56560c78257 not found in /da5_fast/All.sha1c/commit_10.tch'}

 96%|█████████▋| 3077/3194 [1:03:31<02:24,  1.23s/it]

Got Errors {'ded9a39ac3ecee3489e98ada833517df1e8aab32': 'Key ded9a39ac3ecee3489e98ada833517df1e8aab32 not found in /da5_fast/All.sha1c/commit_94.tch'}

100%|██████████| 3194/3194 [1:05:55<00:00,  1.24s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,000b054f839a0eaba1d76e97da534b18df0e41f0,798c2f825ab29c72164485cd199f5a23e2d3029c,[fd6b0cde3513b99336aa9aa892c94bbbb11c8f82],George Artavanis <ga6@verde.princeton.edu>,1729186857,-0400,George Artavanis <ga6@verde.princeton.edu>,1729186857,-0400,Format with black\n,000b054f839a0eaba1d76e97da534b18df0e41f0,parflow_parflow
1,00254de2fe4f77d94ec1b40fe530e01c8cde7804,9cb5f8fc67721d1d6c1794e385cdb577ba2d5df8,[8b7b1168d3eca31db5c77d8059337440e4df3184],kvrigor <kvrigor@users.noreply.github.com>,1732290753,+0100,kvrigor <kvrigor@users.noreply.github.com>,1732290753,+0100,CI: Compile vanilla ParFlow GCC on Ubuntu 24.04\n,00254de2fe4f77d94ec1b40fe530e01c8cde7804,parflow_parflow

In [ ]:
print("Original commits:", len(df))
print("Retrieved commit records:", len(df_commit_data))
print("Missing:", len(df) - len(df_commit_data))
df_commit_data.columns

Original commits: 31937
Retrieved commit records: 31900
Missing: 37

Index(['commit', 'tree', 'parent', 'author', 'author_time', 'author_tz',
       'committer', 'committer_time', 'committer_tz', 'message', 'sha1',
       'project'],
      dtype='object')

In [ ]:
project_summary = (
    df_commit_data
    .groupby('project')
    .agg(
        num_commits=('commit', 'count'),
        num_authors=('author', 'nunique'),
        min_time=('committer_time', 'min'),
        max_time=('committer_time', 'max')
    )
    .reset_index()
)

project_summary

,project,num_commits,num_authors,min_time,max_time
0,google_uis-rnn,199,10,1539291780,1727274796
1,inab_wes-backend,2109,25,1601907721,1762171993
2,knossos-project_knossos,5530,61,1326397084,1761820051
3,leftygray_cascade_calculations,1070,4,1428986446,1740008603
4,nrel_openstudio-server,8818,68,1371703553,1755617530
5,openmd_openmd,3661,54,1095999403,1761583987
6,parflow_parflow,5365,135,1212532785,1776455380
7,project-konda_pattern-based-quality-analysis,3540,16,1576055433,1762359705
8,wistaria_materiappsinstaller,1231,19,1384268877,1759372566
9,wtmatlock_flanker,377,9,1603277905,1734535203

In [ ]:
project_summary['min_time'] = pd.to_datetime(
    project_summary['min_time'],
    unit='s',
    utc=True
)

project_summary['max_time'] = pd.to_datetime(
    project_summary['max_time'],
    unit='s',
    utc=True
)

project_summary

,project,num_commits,num_authors,min_time,max_time
0,google_uis-rnn,199,10,2018-10-11 21:03:00+00:00,2024-09-25 14:33:16+00:00
1,inab_wes-backend,2109,25,2020-10-05 14:22:01+00:00,2025-11-03 12:13:13+00:00
2,knossos-project_knossos,5530,61,2012-01-12 19:38:04+00:00,2025-10-30 10:27:31+00:00
3,leftygray_cascade_calculations,1070,4,2015-04-14 04:40:46+00:00,2025-02-19 23:43:23+00:00
4,nrel_openstudio-server,8818,68,2013-06-20 04:45:53+00:00,2025-08-19 15:32:10+00:00
5,openmd_openmd,3661,54,2004-09-24 04:16:43+00:00,2025-10-27 16:53:07+00:00
6,parflow_parflow,5365,135,2008-06-03 22:39:45+00:00,2026-04-17 19:49:40+00:00
7,project-konda_pattern-based-quality-analysis,3540,16,2019-12-11 09:10:33+00:00,2025-11-05 16:21:45+00:00
8,wistaria_materiappsinstaller,1231,19,2013-11-12 15:07:57+00:00,2025-10-02 02:36:06+00:00
9,wtmatlock_flanker,377,9,2020-10-21 10:58:25+00:00,2024-12-18 15:20:03+00:00

In [ ]:
sydlwils_project_summary = project_summary
print(sydlwils_project_summary)
sydlwils_project_summary.to_csv('sydlwils_project_summary.csv', index=False)

                                        project  num_commits  num_authors  \
0                                google_uis-rnn          199           10
1                              inab_wes-backend         2109           25
2                       knossos-project_knossos         5530           61
3                leftygray_cascade_calculations         1070            4
4                        nrel_openstudio-server         8818           68
5                                 openmd_openmd         3661           54
6                               parflow_parflow         5365          135
7  project-konda_pattern-based-quality-analysis         3540           16
8                  wistaria_materiappsinstaller         1231           19
9                             wtmatlock_flanker          377            9

                   min_time                  max_time
0 2018-10-11 21:03:00+00:00 2024-09-25 14:33:16+00:00
1 2020-10-05 14:22:01+00:00 2025-11-03 12:13:13+00:00
2 2012-01-12 19:38:04+00:00 2025-10-30 10:27:31+00:00
3 2015-04-14 04:40:46+00:00 2025-02-19 23:43:23+00:00
4 2013-06-20 04:45:53+00:00 2025-08-19 15:32:10+00:00
5 2004-09-24 04:16:43+00:00 2025-10-27 16:53:07+00:00
6 2008-06-03 22:39:45+00:00 2026-04-17 19:49:40+00:00
7 2019-12-11 09:10:33+00:00 2025-11-05 16:21:45+00:00
8 2013-11-12 15:07:57+00:00 2025-10-02 02:36:06+00:00
9 2020-10-21 10:58:25+00:00 2024-12-18 15:20:03+00:00

[number of stars, number of forks, last commit date]

https://github.com/parflow/parflow

Stars: 214

Forks: 130

Last Commit Date: 09/15/26


https://github.com/inab/wes-backend

Stars: 21

Forks: 5

Last Commit Date: 09/07/26

https://github.com/knossos-project/knossos

Stars: 77

Forks: 21

Last Commit Date: 05/22/26

https://github.com/project-konda/pattern-based-quality-analysis

Stars: 5

Forks: 3

Last Commit Date: 08/17/26

https://github.com/wistaria/MateriAppsInstaller

Stars: 14

Forks: 14

Last Commit Date: 05/24/26

https://github.com/wtmatlock/flanker

Stars: 37

Forks: 9

Last Commit Date: 12/18/24

https://github.com/OpenMD/OpenMD

Stars: 91

Forks: 35

Last Commit Date: 08/08/26

https://github.com/google/uis-rnn

Stars: 1.6k

Forks: 320

Last Commit Date: 09/25/24

https://github.com/leftygray/Cascade_calculations

Stars: 0

Forks: 0

Last Commit Date: 03/29/26

https://github.com/NREL/OpenStudio-server

Stars: 59

Forks: 27

Last Commit Date: 08/19/26

In [ ]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '000b054f839a0eaba1d76e97da534b18df0e41f0', 'tree': '798c2f825ab29c72164485cd199f5a23e2d3029c', 'parent': ['fd6b0cde3513b99336aa9aa892c94bbbb11c8f82'], 'author': 'George Artavanis <ga6@verde.princeton.edu>', 'author_time': 1729186857, 'author_tz': '-0400', 'committer': 'George Artavanis <ga6@verde.princeton.edu>', 'committer_time': 1729186857, 'committer_tz': '-0400', 'message': 'Format with black\n'}

In [ ]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [ ]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,nrel_openstudio-server,000b054f839a0eaba1d76e97da534b18df0e41f0,George Artavanis <ga6@verde.princeton.edu>,1729186857,Format with black\n

In [ ]:
#mode a means append, so you have all your projects in the same file
yournetid='sydlwils'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github